### ISSUE TITLE
demo page: reduce 40px top margin on mobile?

### ISSUE THREAD

**Issue by benatkin** [tbolt/boltcss#19]
I was evaluating how good it looks on the phone and thought it looked great except the space on the top reduced the amount of content on the front page and looked a bit out of place.

Luckily these aren't styles in bolt itself but on the demo page.

Do you think reducing the margin to half or so on mobile with a media query would be an improvement?

```
.demo-body {
    max-width: 800px;
    margin: 40px auto;
```

<img width="400" alt="Captura de Pantalla 2023-03-20 a la(s) 10 07 14" src="https://user-images.githubusercontent.com/4126/226415297-43bce47c-55cd-45e2-a415-ff7d0d47d7e6.png">

I looked at it some more and I might have changed my mind a bit, but I want to suggest it just in case. Maybe bringing it down to 30px on mobile would make the first impression nicer even though it wouldn't look like much to most comparing them.

**Comment by tbolt** [comment]
Good point. I will cut it in half I think.
