### ISSUE TITLE
Hidden property doesn't work

### ISSUE THREAD

**Issue by rexwithluv** [tbolt/boltcss#23]
When applying hidden directly on the HTML or from JS, it does not work. It still shows the text even if it has the hidden property active.

When bolt is imported
![imagen](https://github.com/user-attachments/assets/58cfa945-e63c-447f-bf3a-7ce69e9eef8c)

When bolt isn't imported
![imagen](https://github.com/user-attachments/assets/a1fdabb4-1e10-460f-808e-9897ad058b16)

**Comment by tbolt** [comment]
Yea, that's likely an issue/bug. This is the current `p` styling-
```css
p {
  display: block;
  line-height: 1.6em;
}
```
I'm not sure why it has `display: block;` I will likely remove it once I test it out.

**Comment by tbolt** [comment]
@rexwithluv I have a PR- https://github.com/tbolt/boltcss/pull/24

Can you test that it fixes your issue? Alternatively just manually remove `display: block;` from the `p` tag in bolt.css

Appreciate you pointing this out.

**Comment by rexwithluv** [comment]
Indeed! When I remove/comment out the `display: block` line in the `<p>`, `hidden` works as expected.

remove `display: block`
![imagen](https://github.com/user-attachments/assets/82a7cbba-8a6b-4565-a12e-96f9fe95f247)

with `display: block`
![imagen](https://github.com/user-attachments/assets/1fffc124-ae5e-4ced-b14b-9b4cdc8e6b86)

**Comment by tbolt** [comment]
Awesome. Great find; I will work on getting a new release rolled out.

**Comment by rexwithluv** [comment]
Thank you very much! Glad to help :)

**Comment by tbolt** [comment]
Published v0.8.0 with a fix for this. Thanks again.
