### ISSUE TITLE
pre should have border

### ISSUE THREAD

**Issue by 89z** [tbolt/boltcss#4]
I was thinking of moving to Bolt from New:

https://github.com/xz/new.css

but with New, `pre` has a border:

~~~css
:root {
   --nc-bg-3: #E5E7EB;
}
pre {
   border: 1px solid var(--nc-bg-3);
}
~~~

you could probably just copy the border style from `<code>`:

https://github.com/tbolt/boltcss/blob/3ba00eec9e5d93b15410837999b31fd5f9277625/bolt.css#L239

**Comment by 89z** [comment]
also I think the `pre` background should match `code` as well:

https://github.com/tbolt/boltcss/blob/3ba00eec9e5d93b15410837999b31fd5f9277625/bolt.css#L237

**Comment by tbolt** [comment]
I agree, I will add a border and have it match `<code>`

**Comment by tbolt** [comment]
Updated in #6 

thanks
