### ISSUE TITLE
list header consistency

### ISSUE THREAD

**Issue by 89z** [tbolt/boltcss#7]
currently looks like this:

https://github.com/tbolt/boltcss/blob/19c65a239d8856a928175297eba4d083b350c176/index.html#L178
https://github.com/tbolt/boltcss/blob/19c65a239d8856a928175297eba4d083b350c176/index.html#L199
https://github.com/tbolt/boltcss/blob/19c65a239d8856a928175297eba4d083b350c176/index.html#L209

something like this might be better:

~~~
description list (dl)
ordered list (ol)
unordered list (ul)
~~~

- https://developer.mozilla.org/docs/Web/HTML/Element/dl
- https://developer.mozilla.org/docs/Web/HTML/Element/ol
- https://developer.mozilla.org/docs/Web/HTML/Element/ul

**Comment by tbolt** [comment]
Updated in https://github.com/tbolt/boltcss/tree/nov2022-updates

**Comment by 89z** [comment]
do you have an estimate for when that branch is getting merged?

**Comment by tbolt** [comment]
Hoping to push a release this week. Would like to provide a minified version with this one.
